swagger: '2.0'
info:
  description: This is a test describing the BIC Boxtech API v2 endpoints.
  version: 2.0.0
  title: BIC Boxtech
  termsOfService: 'https://www.bic-boxtech.org/terms-conditions/'
  contact:
    email: boxtech-admin@bic-boxtech.org
host: box-tech-uat.herokuapp.com
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
basePath: /api/v2.0/
tags:
  - name: container
    description: container operations
    externalDocs:
      description: Find out more
      url: 'https://www.bic-boxtech.org/faqs/'
schemes:
  - https
paths:
  '/container/{container_number}':
    parameters:
      - name: container_number
        in: path
        description: container number of pet to return
        required: true
        type: string
        format: AAAU9999990
      - in: formData
        name: grant_type
        type: string
        description: password.
      - in: formData
        name: username
        type: string
        description: Username.
      - in: formData
        name: password
        type: string
        description: Password.        
    get:
      tags:
        - container
      summary: Find a container by the Container Number
      description: Returns a single container
      operationId: getContainerByNumber
      produces:
        - application/json
      requestBody:
        description: Optional description in *Markdown*
        required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ContainerOut'
        '404':
          description: Container not found in the database
        '409':
          description: >-
            Container concerned by an alert, making it impossible to be queried
            directly
      security:
        - boxtech_auth: []
    delete:
      tags:
        - container
      summary: Inactives a container
      description: >-
        Soft deletes a container, if you want your data to be totally removed,
        please contact us.
      operationId: inactiveContainer
      produces:
        - application/json
      parameters:
        - name: container_number
          in: path
          description: container number to delete
          required: true
          type: string
      responses:
        '400':
          description: Invalid Container number supplied
        '404':
          description: Container not found
      security:
        - boxtech_auth: []
    put:
      tags:
        - container
      summary: Update an existing container
      description: ''
      operationId: updateContainer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: container_number
          in: path
          description: container number to delete
          required: true
          type: string
        - in: body
          name: body
          description: Container object that needs to be updated in the database
          required: true
          schema:
            $ref: '#/definitions/ContainerUpdate'
      responses:
        '400':
          description: Invalid Container Number supplied
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: Container not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        '405':
          description: Validation exception
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
        - boxtech_auth: []
  /container/:
    post:
      tags:
        - container
      summary: Add a new container in the database
      description: ''
      operationId: addContainer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Container object that needs to be added to the database
          required: true
          schema:
            $ref: '#/definitions/ContainerIn'
      responses:
        '400':
          description: Invalid Container Number supplied
        '405':
          description: Invalid input
        '409':
          description: Invalid input
      security:
        - boxtech_auth: []
securityDefinitions:
  boxtech_auth:
    type: apiKey
    name: Authorization
    in: header
    tokenUrl: 'https://bic-boxtech-staging.herokuapp.com/oauth/token'
    

  boxtech_auth:
    type: oauth2
    flow: basic

definitions:
  Alert:
    type: object
    properties:
      type:
        type: string
      description:
        type: string
      message:
        type: string
  ContainerIn:
    type: object
    required:
      - container_number
    properties:
      container_number:
        type: string
        format: AAAU9999990
      tare_kg:
        type: number
        format: float
      tare_lbs:
        type: number
        format: float
      group_st:
        type: string
        format: XXXX
      detail_st:
        type: string
        format: XXXX
      max_payload_kg:
        type: number
        format: float
      max_payload_lbs:
        type: number
        format: float
      max_gross_mass_kg:
        type: number
        format: float
      max_gross_mass_lbs:
        type: number
        format: float
      cubic_capacity_cbm:
        type: number
        format: float
      cubic_capacity_cuft:
        type: number
        format: float
      stacking_kg:
        type: number
        format: float
      stacking_lbs:
        type: number
        format: float
      racking_kg:
        type: number
        format: float
      racking_lbs:
        type: number
        format: float
      racking_n:
        type: number
        format: float
      external_length_mm:
        type: number
        format: float
      external_width_mm:
        type: number
        format: float
      external_height_mm:
        type: number
        format: float
      internal_length_mm:
        type: number
        format: float
      internal_width_mm:
        type: number
        format: float
      internal_height_mm:
        type: number
        format: float
      door_opening_width_mm:
        type: number
        format: float
      door_opening_height_mm:
        type: number
        format: float
      manufacture_number:
        type: number
        format: float
      manufacture_date:
        type: string
        format: '1933-06-30'
      manufacturer:
        type: number
        format: float
      customs_approval:
        type: number
        format: float
      customs_approval_type:
        type: number
        format: float
      csc_approval:
        type: number
        format: float
      timber_treatment_approval:
        type: string
      one_door_off_stacking_kg:
        type: number
        format: float
      one_door_off_stacking_lbs:
        type: number
        format: float
      one_door_off_racking_kg:
        type: number
        format: float
      one_door_off_racking_lbs:
        type: number
        format: float
      one_door_off_racking_n:
        type: number
        format: float
      one_door_off_end_wall_strength_kg:
        type: number
        format: float
      one_door_off_end_wall_strength_lbs:
        type: number
        format: float
  ContainerUpdate:
    type: object
    properties:
      tare_kg:
        type: number
        format: float
      tare_lbs:
        type: number
        format: float
      group_st:
        type: string
        format: XXXX
      detail_st:
        type: string
        format: XXXX
      max_payload_kg:
        type: number
        format: float
      max_payload_lbs:
        type: number
        format: float
      max_gross_mass_kg:
        type: number
        format: float
      max_gross_mass_lbs:
        type: number
        format: float
      cubic_capacity_cbm:
        type: number
        format: float
      cubic_capacity_cuft:
        type: number
        format: float
      stacking_kg:
        type: number
        format: float
      stacking_lbs:
        type: number
        format: float
      racking_kg:
        type: number
        format: float
      racking_lbs:
        type: number
        format: float
      racking_n:
        type: number
        format: float
      external_length_mm:
        type: number
        format: float
      external_width_mm:
        type: number
        format: float
      external_height_mm:
        type: number
        format: float
      internal_length_mm:
        type: number
        format: float
      internal_width_mm:
        type: number
        format: float
      internal_height_mm:
        type: number
        format: float
      door_opening_width_mm:
        type: number
        format: float
      door_opening_height_mm:
        type: number
        format: float
      manufacture_number:
        type: number
        format: float
      manufacture_date:
        type: string
        format: '1933-06-30'
      manufacturer:
        type: number
        format: float
      customs_approval:
        type: number
        format: float
      customs_approval_type:
        type: number
        format: float
      csc_approval:
        type: number
        format: float
      timber_treatment_approval:
        type: string
      one_door_off_stacking_kg:
        type: number
        format: float
      one_door_off_stacking_lbs:
        type: number
        format: float
      one_door_off_racking_kg:
        type: number
        format: float
      one_door_off_racking_lbs:
        type: number
        format: float
      one_door_off_racking_n:
        type: number
        format: float
      one_door_off_end_wall_strength_kg:
        type: number
        format: float
      one_door_off_end_wall_strength_lbs:
        type: number
        format: float
  ContainerOut:
    type: object
    required:
      - container_number
    properties:
      container_number:
        type: string
        format: AAAU9999990
      alert:
        type: array
        items:
          $ref: '#/definitions/Alert'
      tare_kg:
        type: number
        format: float
      tare_lbs:
        type: number
        format: float
      group_st:
        type: string
      detail_st:
        type: string
      max_payload_kg:
        type: number
        format: float
      max_payload_lbs:
        type: number
        format: float
      max_gross_mass_kg:
        type: number
        format: float
      max_gross_mass_lbs:
        type: number
        format: float
      cubic_capacity_cbm:
        type: number
        format: float
      cubic_capacity_cuft:
        type: number
        format: float
      stacking_kg:
        type: number
        format: float
      stacking_lbs:
        type: number
        format: float
      racking_kg:
        type: number
        format: float
      racking_lbs:
        type: number
        format: float
      racking_n:
        type: number
        format: float
      external_length_mm:
        type: number
        format: float
      external_width_mm:
        type: number
        format: float
      external_height_mm:
        type: number
        format: float
      internal_length_mm:
        type: number
        format: float
      internal_width_mm:
        type: number
        format: float
      internal_height_mm:
        type: number
        format: float
      door_opening_width_mm:
        type: number
        format: float
      door_opening_height_mm:
        type: number
        format: float
      manufacture_number:
        type: number
        format: float
      manufacture_date:
        type: number
        format: float
      manufacturer:
        type: number
        format: float
      customs_approval:
        type: number
        format: float
      customs_approval_type:
        type: number
        format: float
      csc_approval:
        type: number
        format: float
      timber_treatment_approval:
        type: number
        format: float
      one_door_off_stacking_kg:
        type: number
        format: float
      one_door_off_stacking_lbs:
        type: number
        format: float
      one_door_off_racking_kg:
        type: number
        format: float
      one_door_off_racking_lbs:
        type: number
        format: float
      one_door_off_racking_n:
        type: number
        format: float
      one_door_off_end_wall_strength_kg:
        type: number
        format: float
      one_door_off_end_wall_strength_lbs:
        type: number
        format: float
  ErrorResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
